// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/iniyusril/presence-api/api/server"
	"github.com/iniyusril/presence-api/command/cmdaction"
	"github.com/iniyusril/presence-api/command/cmdservice"
	"github.com/iniyusril/presence-api/config"
	"github.com/iniyusril/presence-api/query/qryaction"
	"github.com/iniyusril/presence-api/query/qryservice"
	"github.com/iniyusril/presence-api/repository"
	"github.com/iniyusril/presence-api/route"
	"github.com/labstack/echo/v4"
)

// Injectors from inject.go:

func InitializedServer() *echo.Echo {
	db := config.NewDb()
	userRepository := repository.NewUserRepository(db)
	userCommandAction := cmdaction.NewUserCommandAction(userRepository)
	userService := cmdservice.NewUserService(userCommandAction, db)
	userQueryAction := qryaction.NewUserQueryAction(userRepository)
	userQueryService := qryservice.NewUserQueryService(userQueryAction)
	userServer := server.NewUserServer(userService, userQueryService)
	echoEcho := route.NewRoute(userServer)
	return echoEcho
}

// inject.go:

var userSet = wire.NewSet(repository.NewUserRepository, cmdaction.NewUserCommandAction, cmdservice.NewUserService, qryaction.NewUserQueryAction, qryservice.NewUserQueryService, server.NewUserServer)
